De-Linting recipes.
*	apr_util
	Added PATCHES to recipe, some cleaning up.
	Won't build, even though I cleaned out the repository folder:

	"[Errno -2147459069] No such file or directory:
	'/HiQ-Data/sources/haikuports/repository/apr_util-1.3.10.DependencyInfo'"

*	arc
	Improved DESCRIPTION
	Won't build:

	/sources/arc-5.21p/arc.c: In function `main':
	/sources/arc-5.21p/arc.c:231: parse error before `int'
	/sources/arc-5.21p/arc.c:232: `fd' undeclared (first use in this function)
	/sources/arc-5.21p/arc.c:232: (Each undeclared identifier is reported only once
	/sources/arc-5.21p/arc.c:232: for each function it appears in.)

*	bc
	Supply the correct pachset name.
	Improved SUMMARY.
	Minor cosmetics.

*	beshare
	Removed missing patchset which was declared alongside the existing one.
	Minor cosmetics.

*	brexx
	Added PATCHES to the recipe.
	Minor cosmetics.
	Won't build:

	/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/i586-pc-haiku/bin/ld: cannot find -lPortManager
	collect2: ld returned 1 exit status
	make[1]: *** [obj/rx] Error 1
	make[1]: Leaving directory `/sources/BeBRexx/src'
	make: [brexx] Error 2 (ignored)
	Collecting files to be packaged ...
	Error: Couldn't access "/sources/BeBRexx/PortManager/obj/PortManager": No such file or directory

*	cd
	Improved SUMMARY.
	Minor cosmetics.
	Won't build:

	Fetching package for devel:libim ...
	*** failed to find a match for "devel:libim": Name not found

*	celestia
	Improved SUMMARY.
	Minor cosmetics.

*	chmlib
	Removed "." from SUMMARY.
	Minor cosmetics.

*	colorcode
	Removed "." from SUMMARY.
	Minor cosmetics.

*	command_not_found
	Removed "(C)" from copyright.
	Created a proper patchset from the provided patch.
	Added PATCHES. Remove manual patching from INSTALL().
	Minor cosmetics.

*	coveredcalc
	Removed "." from SUMMARY.
	Minor cosmetics.
	Added cmd:svn to BUILD_PREREQUIRES.

*	cyberdogs_sdl
	Improved and removed "." from SUMMARY.
	Minor cosmetics.