opencascade: switch to the official version (version 7.7.0)
 * completely rewrite the recipe and the patchset
 * add all supported libraries and optional dependencies that are available
 * tools (command line only) and samples are provided as subpackages
 * Tk (and therefore the GUI for DRAW) is not enabled because it hangs on my system
 * Xlibe is used to provide a window system
   * using both Tk and Xlibe at once is currently not possible due to #7501
   * the patchset contains a commit with a stub allowing at least to build without Xlibe, but there is no proper Haiku implementation of it yet. That code path is currently not used.
 * EGL is used as OpenGL API, but it doesn't work currently. It displays the following error message:
    ```
    Error: EGL does not provide compatible configurations
    ```

Test report:
 * there are 21000 test cases, so the tests take a while to run
 * most tests are skipped due to missing test data (am I missing something how to invoke the tests?)
 * the tests involving the Inspector crash into the Debugger because both Xlibe and Qt5 try to create a BApplication when running the Inspector from DRAW (see threedeyes/qthaikuplugins#27)
 * some tests hang, pegging one core (although they should have a timeout apparently), they must be aborted manually by killing the secondary DRAWEXE
 * the detailed test results are created in $sourceDir/build/results, that folder has 168 MiB zipped