gnutls: build the test targets with -lgnu as they need memmem(3).
* Without the "-lgnu" we would get an undefined reference to `memmem'
  in function hsk_hook_cb (resume_x509-resume.o from tests/resume.c)
* Define TEST_REQUIRES instead of TEST_PREREQUIRES, and drop cmd:cvs
  from it, as cvs is currently failing to build on x86_64.
* No need to revbump as the changes only affect TEST().