libgpg_error: bump to 1.29, add debuginfo. PROVIDES += cmd:yat2m (#2444)
* Add LIBS="-lnetwork" for the logging API, added in 1.28.
* Move $manDir/man1/gpg-error-config.1 to the devel package.
* Remove $manDir and $infoDir when building for a secondary arch.