tqdm: update to version 4.66.1 (#9363)
- Switched build to use build/installer.
- Switched default version to Python 3.10.
- Only install man page / bash completions for the default
  Python version.
- Changed SOURCE_URI to avoid:
  > LookupError: setuptools-scm was unable to detect version
  for /sources/tqdm-4.66.1.

  (that error message suggested using PyPI's tarballs instead
  of Github ones)