Rust: update from-source recipe to 1.79, disable on x86_64
Build fails with:

```
error[E0463]: can't find crate for `core`

error[E0463]: can't find crate for `std`

For more information about this error, try `rustc --explain E0463`.
```

The relevant bit of the "explain":

```
Common causes for missing std or core
*   You are cross-compiling for a target which doesn't have std prepackaged. Consider one of the
    following:
    + Adding a pre-compiled version of std with rustup target add
    + Building std from source with cargo build -Z build-std
    + Using #![no_std] at the crate root, so you won't need std in the first place.
*   You are developing the compiler itself and haven't built libstd from source. You can usually build it with x.py build library/std. More
    information about x.py is available in the rustc-dev-guide.
```

Since I know nothing about Rust, my efforts stop here for today.
According to the git log, this seems to be the same state we were in the
1.73 recipe.